### ISSUE TITLE
Problem with Windows CLI

### ISSUE THREAD

**Issue by kimsonvu** [marph91/jimmy#6] opened 2024-06-20 13:27 UTC
**Describe the bug**
Windows 11 CMD import from synology_note_station format.
Export from Note Station version: 2.6.5-3801

**OS**
Windows 11 x64
Export from Note Station version: 2.6.5-3801

**To Reproduce**
run follow command:
C:\Users\user\Downloads\jimy-cli import>jimmy-cli-windows.exe 20240620_195441_27846.nsx --format synology_note_station

Error:
[INFO ] Importing notes from 20240620_195441_27846.nsx
[INFO ] Start parsing
Traceback (most recent call last):
  File "jimmy_cli.py", line 66, in <module>
  File "jimmy_cli.py", line 62, in main
  File "jimmy.py", line 130, in jimmy
  File "jimmy.py", line 69, in convert_all_inputs
  File "converter.py", line 55, in convert_multiple
  File "formats\synology_note_station.py", line 106, in convert
  File "formats\synology_note_station.py", line 67, in convert_notebooks
  File "pathlib.py", line 1059, in read_text
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 91: character maps to <undefined>
[12832] Failed to execute script 'jimmy_cli' due to unhandled exception!

![WindowsTerminal_RXWw8OQMj3](https://github.com/marph91/jimmy/assets/10061253/d73c8ced-e32c-4d98-9a0e-164ad9038478)

**Comment by marph91** [comment] 2024-06-20 15:23
Somehow the windows CI didn't have this issue, but I was able to reproduce it locally in a windows VM.

It should be fixed in the latest release 0.0.3 (by commit https://github.com/marph91/jimmy/commit/38b9d45618e48ba51ace4ad57c92266ed382a86d). Can you try that?

**Comment by kimsonvu** [comment] 2024-06-21 03:36
> Somehow the windows CI didn't have this issue, but I was able to reproduce it locally in a windows VM.
> 
> It should be fixed in the latest release 0.0.3 (by commit [38b9d45](https://github.com/marph91/jimmy/commit/38b9d45618e48ba51ace4ad57c92266ed382a86d)). Can you try that?

It work now. Thank you to fix and glad to inform to you.

**Comment by kimsonvu** [comment] 2024-06-21 03:37
> Somehow the windows CI didn't have this issue, but I was able to reproduce it locally in a windows VM.
> 
> It should be fixed in the latest release 0.0.3 (by commit [38b9d45](https://github.com/marph91/jimmy/commit/38b9d45618e48ba51ace4ad57c92266ed382a86d)). Can you try that?

Hi Jimmy,

Is it possible to import full 1 folder than one *.nsx file each time?

**Comment by kimsonvu** [comment] 2024-06-21 04:14
Hi Jimmy,

After i tested with a big file 4Gb *.nsx. It shows this erros:

[INFO ] Start parsing
Traceback (most recent call last):
  File "jimmy_cli.py", line 66, in <module>
  File "jimmy_cli.py", line 62, in main
  File "jimmy.py", line 83, in jimmy
  File "jimmy.py", line 68, in convert_all_inputs
  File "converter.py", line 55, in convert_multiple
  File "formats\synology_note_station.py", line 121, in convert
  File "formats\synology_note_station.py", line 91, in map_resources_by_hash
  File "<string>", line 6, in __init__
  File "intermediate_format.py", line 40, in __post_init__
  File "common.py", line 37, in is_image
  File "puremagic\main.py", line 267, in from_file
  File "puremagic\main.py", line 200, in _magic
  File "puremagic\main.py", line 193, in _identify_all
  File "puremagic\main.py", line 134, in _confidence
puremagic.main.PureError: Could not identify file
[10528] Failed to execute script 'jimmy_cli' due to unhandled exception!

**Comment by marph91** [comment] 2024-06-21 07:15
Hi @kimsonvu,

> puremagic.main.PureError: Could not identify file
[10528] Failed to execute script 'jimmy_cli' due to unhandled exception!

This should be fixed by [release 0.0.4](https://github.com/marph91/jimmy/releases/tag/v0.0.4).

> Is it possible to import full 1 folder than one *.nsx file each time?

`jimmy` supports only `.nsx` files. I don't have access to synology note station right now. Maybe there is an export option to export a single folder (https://kb.synology.com/en-global/DSM/help/NoteStation/note_station_managing_notes?version=7#t7).

**Comment by kimsonvu** [comment] 2024-06-21 07:32
> Hi @kimsonvu,
> 
> > puremagic.main.PureError: Could not identify file
> > [10528] Failed to execute script 'jimmy_cli' due to unhandled exception!
> 
> This should be fixed by [release 0.0.4](https://github.com/marph91/jimmy/releases/tag/v0.0.4).
> 
> > Is it possible to import full 1 folder than one *.nsx file each time?
> 
> `jimmy` supports only `.nsx` files. I don't have access to synology note station right now. Maybe there is an export option to export a single folder (https://kb.synology.com/en-global/DSM/help/NoteStation/note_station_managing_notes?version=7#t7).

Test and found this errors:

Traceback (most recent call last):
  File "jimmy_cli.py", line 71, in <module>
  File "jimmy_cli.py", line 67, in main
  File "jimmy.py", line 103, in jimmy
  File "jimmy.py", line 73, in convert_all_inputs
  File "converter.py", line 55, in convert_multiple
  File "formats\synology_note_station.py", line 121, in convert
  File "formats\synology_note_station.py", line 81, in map_resources_by_hash
AttributeError: 'NoneType' object has no attribute 'values'
[26580] Failed to execute script 'jimmy_cli' due to unhandled exception!

**Comment by marph91** [comment] 2024-06-21 11:06
> File "formats\synology_note_station.py", line 81, in map_resources_by_hash
AttributeError: 'NoneType' object has no attribute 'values'
[26580] Failed to execute script 'jimmy_cli' due to unhandled exception!

I think I fixed this exception, but can release it only later today or tomorrow.

Is there a way you could provide the file (or even better a minimal example) to me? I could go through all potential errors and fix them at once. I can give you my mail address if needed.

**Comment by kimsonvu** [comment] 2024-06-21 12:34
> > File "formats\synology_note_station.py", line 81, in map_resources_by_hash
> > AttributeError: 'NoneType' object has no attribute 'values'
> > [26580] Failed to execute script 'jimmy_cli' due to unhandled exception!
> 
> I think I fixed this exception, but can release it only later today or tomorrow.
> 
> Is there a way you could provide the file (or even better a minimal example) to me? I could go through all potential errors and fix them at once. I can give you my mail address if needed.

Hi Jimmy,

Take your time. I just tested this script to export to Joplin because i am new to Joplin.
My data on Synology note is big about 4Gb and includes my personal data. 
Some notes encrypt. Do you think it happened to problem?
The successful test that doesn't include any encrypt note.

**Comment by marph91** [comment] 2024-06-21 15:26
Should be fixed with [release 0.0.5](https://github.com/marph91/jimmy/releases/tag/v0.0.5).

> My data on Synology note is big about 4Gb and includes my personal data.
Some notes encrypt. Do you think it happened to problem?

Encrypted notes aren't the root cause of this problem. I think my small test data didn't cover all the edge cases of real data (like yours). So there might be even more problems. But it's good to fix them and I'm happy to improve the code. For now the fixes to the problems are obvious, so I can do them without actually knowing the source data.

It won't be possible to convert encrypted notes for now. They should be ignored. (It would require to implement their decryption algorithm. I didn't find any documentation about it.)

Btw. the name of the project is jimmy. My nickname is marph :)

**Comment by kimsonvu** [comment] 2024-06-22 04:09
Hi,

I found this problem for v005

Traceback (most recent call last):
  File "jimmy_cli.py", line 71, in <module>
  File "jimmy_cli.py", line 67, in main
  File "jimmy.py", line 103, in jimmy
  File "jimmy.py", line 73, in convert_all_inputs
  File "converter.py", line 55, in convert_multiple
  File "formats\synology_note_station.py", line 123, in convert
  File "formats\synology_note_station.py", line 93, in map_resources_by_hash
  File "<string>", line 6, in __init__
  File "intermediate_format.py", line 40, in __post_init__
  File "common.py", line 38, in is_image
  File "puremagic\main.py", line 267, in from_file
  File "puremagic\main.py", line 199, in _magic
ValueError: Input was empty
[26584] Failed to execute script 'jimmy_cli' due to unhandled exception!

**Comment by marph91** [comment] 2024-06-22 06:55
Fixed in release 0.0.6.

For the next try, could you use the following command? (i. e. appending the `--log` and `--dry-run` flags)

`jimmy-cli-windows.exe 20240620_195441_27846.nsx --format synology_note_station --log --dry-run`

This will create a log file called `jimmy.log` next to `jimmy-cli-windows.exe` that shows hopefully all the remaining problems. Could you upload that here? (It contains the note titles. If there is sensitive information, feel free to delete it.)

**Comment by kimsonvu** [comment] 2024-06-22 09:56
Hi,

Please check log on this comment. I found problem while data fill into Joplin? I already create blank joplin database to import to test.

  File "importer.py", line 28, in add_tag                                                               File "joppy\api.py", line 344, in add_tag
  File "joppy\api.py", line 97, in post
  File "joppy\api.py", line 74, in _request
  File "requests\models.py", line 1024, in raise_for_status
requests.exceptions.HTTPError: ('500 Server Error: Internal Server Error for url: http://localhost:41184/tags?token=b367112a2c31ff9b29c0b139fbf30267bf49811b143143ebf0285cf82d32e153e6c5b84c3b5cd0149f7759cee7faa8caa0a6676ed7959c656d6e8e8d8af9974f', '{"error":"Internal Server Error: The tag \\"gđkx\\" already exists. Please choose a different name.: \\n\\nError: The tag \\"gđkx\\" already exists. Please choose a different name.\\n    at Tag.<anonymous> (C:\\\\Program Files\\\\Joplin\\\\resources\\\\app.asar\\\\node_modules\\\\@joplin\\\\lib\\\\models\\\\Tag.js:219:31)\\n    at Generator.next (<anonymous>)\\n    at fulfilled (C:\\\\Program Files\\\\Joplin\\\\resources\\\\app.asar\\\\node_modules\\\\@joplin\\\\lib\\\\models\\\\Tag.js:5:58)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jimmy_cli.py", line 71, in <module>
  File "jimmy_cli.py", line 67, in main
  File "jimmy.py", line 114, in jimmy
  File "importer.py", line 81, in import_notebook
  File "importer.py", line 78, in import_notebook
  File "importer.py", line 70, in import_note
[jimmy.log](https://github.com/user-attachments/files/15936083/jimmy.log)

  File "importer.py", line 39, in add_tag
AssertionError
[34048] Failed to execute script 'jimmy_cli' due to unhandled exception!
                                                                                                      Notebooks    4%|██▌                                                            |   4/101 [00:08<03:13]Notes        2%|█                                                            |   52/2628 [00:08<06:33]Resources    4%|██                                                           |   84/2367 [00:08<03:37]Tags         2%|█                                                            |   46/2958 [00:08<08:35]
C:\Users\user\Downloads\jimmy-cli>

**Comment by marph91** [comment] 2024-06-22 14:11
In short: You can try again with [release 0.0.7](https://github.com/marph91/jimmy/releases/tag/v0.0.7).

---

Longer version:

There are 2 problems:

1. The exception when adding the tag `gđkx` in Joplin. I couldn't reproduce it locally, but I added a workaround and more log output.
2. Many resources couldn't be converted (the log says 675 out of 2367). I added more log output, but unfortunately, I can't fix it without an example `.nsx` export.

**Comment by kimsonvu** [comment] 2024-06-23 09:48
> In short: You can try again with [release 0.0.7](https://github.com/marph91/jimmy/releases/tag/v0.0.7).
> 
> Longer version:
> 
> There are 2 problems:
> 
> 1. The exception when adding the tag `gđkx` in Joplin. I couldn't reproduce it locally, but I added a workaround and more log output.
> 2. Many resources couldn't be converted (the log says 675 out of 2367). I added more log output, but unfortunately, I can't fix it without an example `.nsx` export.

Hi marph91,

It work for your last version but i found 2 little errors:

- Tags say like this but tags import fine to Joplin Database.
Screenshot:
![0efA4PIReQ](https://github.com/marph91/jimmy/assets/10061253/b4e74c19-1c7e-456e-a9af-2cd5ff6653b7)



- Tablet on Synology Note Station don't import any data.

![Joplin_xGbxlWGJ3V](https://github.com/marph91/jimmy/assets/10061253/18bc5cfe-e23a-443d-97be-4d4688093e6d)

**Comment by kimsonvu** [comment] 2024-06-23 09:52
Hi ,

More screenshot about table imports wrong:
![5QXcY6Eluh](https://github.com/marph91/jimmy/assets/10061253/4ac6b7e9-940d-4c47-8e25-7b793fd40af7)

**Comment by marph91** [comment] 2024-06-23 13:05
Regarding the tables: I have an `.nsx` file where tables are imported correctly. So it should work in general. I would need an example export to investigate this further (same as for the resources).

Regarding the tags: I can reproduce this. It's likely an issue with vietnamese (?) upper case letters:

- `Điện` doesn't work
- `điện` works
- `Dien` works

I will investigate this.

**Comment by marph91** [comment] 2024-07-07 09:16
The issues are now at the [documentation page](https://marph91.github.io/jimmy/formats/synology_note_station/#known-limitations). If you have any other issue, feel free to reopen this github issue.

**Closed by marph91** 2024-07-07 09:16 UTC
Labels: bug, synology-note-station
